---
- hosts: respaldo
  sudo: yes
  tasks:

    - name: Actualizar paquetes
      apt: update_cache=yes


###########################################   S Q U I D


    - name: Instalar Squid
      apt: name=squid3 state=latest  

    - name: Configurar squid.conf
      template: src=template/squid.conf dest=/etc/squid3/ owner=root mode=0640 backup=yes

    - name: Configurar squid.conf
      template: src=template/nowebs dest=/etc/squid3/ owner=root mode=0640 backup=yes
      
    - name: Copiar listas negras para Squid
      template: src=template/easylist.txt dest=/etc/squid3/ owner=root mode=0640 backup=yes
      
    - name: Reiniciar el servicio Squid
      service: name=squid3 state=restarted


###########################################   D A N S G U A R D I A N    


    - name: Instalar Dansguardian
      apt: name=dansguardian state=latest

    - name: Configurar Dansguardian
      template: src=template/dansguardian.conf dest=/etc/dansguardian/ owner=root mode=0640 backup=yes

    - name: Configurar Dansguardian
      template: src=template/bannedsitelist dest=/etc/dansguardian/lists/ owner=root mode=0640 backup=yes

    - name: Reiniciar el servicio Dansguardian
      service: name=dansguardian state=restarted


###########################################   W E B M I N    


    - name: Lista de paquetes a instalar de Webmin
      apt: name={{item}} state=installed
      with_items:
        - perl
        - libnet-ssleay-perl
        - openssl
        - libauthen-pam-perl
        - libpam-runtime
        - libio-pty-perl
        - apt-show-versions
        - python
        - apache2

    - name: Descargar el paquete Webmin
      copy: src=archive/webmin_1.881_all.deb dest=/home/ owner=root mode=0640 backup=yes

    - name: Instalando Webmin
      shell: dpkg --install /home/webmin_1.881_all.deb
      
    - name: Reiniciar Webmin
      service: name=webmin state=restarted
      

###########################################   F A I L 2 B A N   


    - name: Instalar Fai2ban
      apt: pkg=fail2ban state=latest

    - name: Configurar Fail2ban
      template: src=template/jail.conf dest=/etc/fail2ban/ owner=root mode=0640 backup=yes     

    - name: Reinciar servicio Fail2ban
      service: name=fail2ban state=restarted enabled=yes


##########################################  S A R G


    - name: Instalar Sarg
      apt: name=sarg state=latest

    - name: Configurar Sarg
      template: src=template/sarg.conf dest=/etc/sarg/ owner=root mode=0640 backup=yes

    - name: Programando informes diarios a las 19h
      template: src=template/crontab dest=/etc/ owner=root mode=0640 backup=yes

    - name: Reiniciando el programado de los informes
      service: name=cron state=restarted enabled=yes


##########################################  R E D 


    - name: Configurar la red del servidor
      template: src=template/interfaces dest=/etc/network/ owner=root mode=0640 backup=yes

    - name: Reinciar servicio de red
      service: name=networking state=restarted enabled=yes


##########################################  I P T A B L E S 


    - name: Copiando Iptables al servidor
      template: src=template/iptables.sh dest=/etc/init.d/ owner=root mode=0640 backup=yes

    - name: Configurando Iptables al inicio de cada encendido
      shell: update-rc.d iptables.sh defaults 99

    - name: Dar permisos para la ejecución al inicio
      shell: chmod +x /etc/init.d/iptables.sh




